service: dare-guardians-bot

provider:
  name: aws
  runtime: python3.11
  architecture: arm64
  stage: production
  region: eu-west-1
  deploymentBucket:
    serverSideEncryption: AES256
    blockPublicAccess: true
  environment:
    TELEGRAM_TOKEN: ${env:TELEGRAM_TOKEN}
    DYNAMO_TABLE: ${env:DYNAMO_TABLE}
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:eu-west-1:${env:AWS_ACCOUNT_ID}:table/${env:DYNAMO_TABLE}"

package:
  individually: true
  patterns:
    - "!./**"

functions:
  guardians-listen:
    handler: main.handler
    memorySize: 256
    timeout: 120
    environment:
      GAME_PASSWORD: ${env:GAME_PASSWORD}
    url: true
    package:
      patterns:
        - "main.py"
        - "commands/**"

plugins:
  - serverless-python-requirements
