name: Deploy
run-name: ${{ github.actor }} is dpeloying the app 🚀
on:
  release:
    types: [published]
env:
  TELEGRAM_TOKEN: ${{ vars.TELEGRAM_TOKEN }}
  DYNAMO_TABLE: ${{ vars.DYNAMO_TABLE }}
  AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ vars.AWS_SECRET_ACCESS_KEY }}
  AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
  GAME_PASSWORD: ${{ vars.GAME_PASSWORD }}
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: pip install -r requirements.txt
      - run: npm install -g serverless
      - run: sls plugin install -n serverless-python-requirements
      - run: sls deploy
